version: "3.8"

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.7
    restart: always
    ports:
      - "8093:8080"   
      - "50051:50051" 
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      - t2v-transformers

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    restart: always
    environment:
      ENABLE_CUDA: '0'          
      INFERENCE_API_KEY: ''    
    ports:
      - "8092:8080"             

volumes:
  weaviate_data:
